// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmfvKqlpbmIO4J-Zu809Xu0Q-tmCRxaW8',
    appId: '1:831960708708:web:ba65f7d95b9689d9509171',
    messagingSenderId: '831960708708',
    projectId: 'cinema-29555',
    authDomain: 'cinema-29555.firebaseapp.com',
    storageBucket: 'cinema-29555.appspot.com',
    measurementId: 'G-FJLMRKJ92Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8pR-aVUgkfvdjkGRDGsUjGIpwbzIuobc',
    appId: '1:831960708708:android:0a7b17de331dac33509171',
    messagingSenderId: '831960708708',
    projectId: 'cinema-29555',
    storageBucket: 'cinema-29555.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGOrsnej0X6loyK7rVV1NBkUIQupL0GLY',
    appId: '1:831960708708:ios:63b6fc280284ceb9509171',
    messagingSenderId: '831960708708',
    projectId: 'cinema-29555',
    storageBucket: 'cinema-29555.appspot.com',
    iosClientId: '831960708708-6gbmibsk3jc5u68s34hm9983k7d0d4cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGOrsnej0X6loyK7rVV1NBkUIQupL0GLY',
    appId: '1:831960708708:ios:63b6fc280284ceb9509171',
    messagingSenderId: '831960708708',
    projectId: 'cinema-29555',
    storageBucket: 'cinema-29555.appspot.com',
    iosClientId: '831960708708-6gbmibsk3jc5u68s34hm9983k7d0d4cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinema',
  );
}
